# Generated by Django 6.0.4 on 2026-05-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Enter customer comment: ', max_length=3000)),
            ],
        ),
    ]
